version: '3'

services:

  # a simple rabbitMQ
    rabbitmq:
      image: rabbitmq:3-management-alpine 

      labels:
        NAME: "rabbitmq"

      hostname: rabbitmq
      container_name: rabbitmq

      environment:
        RABBITMQ_ERLANG_COOKIE: "QWERTYASDFGHZXCVBN01"
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
        RABBITMQ_DEFAULT_VHOST: "/"

      ports:
        - "4369:4369"
        - "5671:5671"
        - "5672:5672"
        - "15671:15671"
        - "15672:15672"
        - "25672:25672"
        - "1883:1883" 

      expose:
        - "4369"
        - "5671"
        - "5672"
        - "15671"
        - "15672"
        - "25672"
        - "1883"
      
      volumes:
        - ../volumes/data/rabbitmq:/data/

  # the pluto running instance 
    pluto:
      image: python:3.6-slim

      labels:
        NAME: "pluto"

      hostname: pluto
      container_name: pluto

      volumes:
        - ../volumes/data/python:/data/
        - ../volumes/apps/python:/app/
        - ../volumes/apps/python/pluto:/pluto/

      links:
        - rabbitmq:rabbitmq

      depends_on:
        - rabbitmq
        
      restart: unless-stopped
      command: tail -f /dev/null
      # command: bash -c "cd app/setup/ ; ./setup.sh ; cd ../pluto ; python ./infer_service.py"
    