version: '3'

services:

  # a simple rabbitMQ
    hermesmq:
      image: rabbitmq:3-management-alpine 

      labels:
        NAME: "hermesmq"

      hostname: hermesmq
      container_name: hermesmq

      environment:
        RABBITMQ_ERLANG_COOKIE: "QWERTYASDFGHZXCVBN01"
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
        RABBITMQ_DEFAULT_VHOST: "/"

      ports:
        - "5548:5672"
        - "15548:15672"

      expose:
        - "5548"
        - "15548"
      
      volumes:
        - ../../volumes/data/hermesmq:/data/


  # the HERMES running instance 
    hermes:
      image: ohiaia/gaia:hermes

      labels:
        NAME: "hermes"

      hostname: hermes
      container_name: hermes

      volumes:
        - ../../hermes:/hermes/
        # Change this to "kosmo"
        - ../../volumes/data/hermes:/data/
        # Automation will remove this
        - ../:/CHAOS/     

      links:
        - hermesmq:hermesmq

      depends_on:
        - hermesmq
        
      restart: unless-stopped
      entrypoint: /bin/bash 
      command: ./CHAOS/stack/start.sh 
    
    
  # a java docker for the sdk 
    sdk:
      image: java:8-jdk

      labels:
        NAME: "sdk"

      hostname: "sdk"
      container_name: "sdk"

      volumes:
        - ../../sdk:/sdk/

      links:
        - hermesmq:hermesmq

      depends_on:
        - hermesmq
        
      restart: unless-stopped
      command: tail -f /dev/null