version: '3'

services:

  # a simple rabbitMQ
    hermesmq:
      image: rabbitmq:3-management-alpine 

      labels:
        NAME: "hermesmq"

      hostname: hermesmq
      container_name: hermesmq

      environment:
        RABBITMQ_ERLANG_COOKIE: "QWERTYASDFGHZXCVBN01"
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
        RABBITMQ_DEFAULT_VHOST: "/"

      ports:
        - "5673:5672"
        - "15673:15672"

      expose:
        - "5673"
        - "15673"
      
      volumes:
        - ../volumes/data/hermesmq:/data/

  # the hermes running instance 
    hermes:
      # image: python:3.6-slim
      image: ohiaia/gaia:hermes

      labels:
        NAME: "hermes"

      hostname: hermes
      container_name: hermes

      env_file:
        - ../settings/config.sh

      volumes:
        - ../../hermes:/hermes/
        - ../:/CHAOS/        
        - ../volumes/data/hermes:/data/

      # links:
      #   - hermesmq:hermesmq

      # depends_on:
      #   - hermesmq
        
      restart: unless-stopped
      entrypoint: /bin/bash 
      command: ./CHAOS/stack/hermes.sh 
        # tail -f /dev/null
      # command: bash -c "cd app/setup/ ; ./setup.sh ; cd ../pluto ; python ./infer_service.py"
    