version: '3'

services:

  # a simple rabbitMQ
    plutomq:
      image: rabbitmq:3-management-alpine 

      labels:
        NAME: "plutomq"

      hostname: "plutomq"
      container_name: "plutomq"

      environment:
        RABBITMQ_ERLANG_COOKIE: "QWERTYASDFGHZXCVBN01"
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
        RABBITMQ_DEFAULT_VHOST: "/"

      ports:
        - "5672:5672"
        - "15672:15672"

      expose:
        - "5672"
        - "15672"
      
      volumes:
        - ../../volumes/data/plutomq:/data/


  # the PLUTO running instance 
    pluto:
      image: python:3.6-slim

      labels:
        NAME: "pluto"

      hostname: "pluto"
      container_name: "pluto"

      volumes:
        - ../../pluto:/pluto/
        # Change this to "kosmo"
        - ../../volumes/data/pluto:/data/
        # Automation will remove this
        - ../:/CHAOS/

      links:
        - plutomq:plutomq

      depends_on:
        - plutomq
        
      restart: unless-stopped
      command: ./CHAOS/stack/start.sh 
 
 
  # a java docker for the sdk 
  # for testing purposes

    # sdk:
    #   image: java:8-jdk

    #   labels:
    #     NAME: "sdk"

    #   hostname: "sdk"
    #   container_name: "sdk"

    #   volumes:
    #     - ../../sdk:/sdk/

    #   links:
    #     - plutomq:plutomq

    #   depends_on:
    #     - plutomq
        
    #   restart: unless-stopped
    #   command: tail -f /dev/null
      